swagger: "2.0"
info:
  version: "1.0.0"
  title: My API
  description: A simple example of a Swagger file with GET, POST, DELETE methods and multiple URL parameters.
paths:
  /:
    get:
      summary: Retrieve a list of users
      operationId: getUsers
      responses:
        200:
          description: A list of users
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
  /auth/login:
    post:
      summary: Login
      operationId: login
      parameters:
        - name: username
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
      responses:
        200:
          description: The user was logged in
          schema:
            $ref: "#/definitions/User"
  /users/{id}/{status}:
    get:
      summary: Retrieve a user by id and status
      operationId: getUser
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: status
          in: path
          required: true
          type: string
      responses:
        200:
          description: A user
          schema:
            $ref: "#/definitions/User"
    post:
      summary: Update a user by id and status
      operationId: updateUser
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: status
          in: path
          required: true
          type: string
        - name: user
          in: body
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: The updated user
          schema:
            $ref: "#/definitions/User"
    delete:
      summary: Delete a user by id and status
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: status
          in: path
          required: true
          type: string
      responses:
        204:
          description: The user was deleted


definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      age:
        type: integer
      status:
        type: string
